module.exports = {
  MEDIA_PATH: '/home/pi/Monitor',
  MEDIA_SERVER_IP: '10.0.0.17',
  MEDIA_SERVER_PROTO: 'http',
  MEDIA_SERVER_PORTS: {
    FEED_1: '8081',
    FEED_2: '8082',
    CONTROL: '8080',
  },
  DEFAULT_USERNAME: 'carl',
  DEFAULT_PASSWORD_HASH: 'REPLACE_ME_WITH_A_BCRYPT_HASH_OF_YOUR_PASSWORD',
};
